### ISSUE TITLE
Unnecessary permissions?

### ISSUE THREAD

**Issue by nyx-lyb3ra** [flathub/io.gitlab.liferooter.TextPieces#6]
It seems to be asking permissions for `~/.local/share/textpieces`, but I think it should be using `~/.var/app/io.gitlab.liferooter.TextPieces/data` instead

Also seems to be asking to talk to Flatpak itself via D-Bus... why?

**Comment by liferooter** [comment]
> It seems to be asking permissions for `~/.local/share/textpieces`, but I think it should be using `~/.var/app/io.gitlab.liferooter.TextPieces/data` instead

Yes, it uses `~/.var/app/io.gitlab.liferooter.TextPieces/data` to store its data. But in the past it used `~/.local/share/textpieces` to workaround some old portal bug and then just because of historical reasons. Now it uses this permission to migrate the data from that directory to the appropriate one.

> Also seems to be asking to talk to Flatpak itself via D-Bus... why?

To run user-defined scripts outside the sandbox. Imagine you've written a script for a custom action for doing some stuff using some Python library for that stuff and then found out that you have to get into the sandbox somehow and install somewhere in here your Python module. And you just can't use Ruby because there's no Ruby inside the sandbox. And also your script cannot read your favourite formatter global configuration file because it's not passed into the sandbox. Running user-defined actions outside the sandbox helps to prevent all these problems and make Flatpak sandbox transparent to the user. The application never runs anything outside the sandbox except scripts that you write by yourself.

**Comment by nyx-lyb3ra** [comment]
I see, then I think the `~/.local/share/textpieces` one should be read only at least

**Comment by liferooter** [comment]
No, because I move files out of it
